FROM node:20.6.1

WORKDIR /usr/src/app

ARG REACT_APP_ONESIGNAL_APP_ID
ARG REACT_APP_ONESIGNAL_SAFARI_WEB_ID
ARG REACT_APP_OIDC_CLIENT_ID
ARG REACT_APP_OIDC_REDIRECT_URI

ENV REACT_APP_ONESIGNAL_APP_ID=$REACT_APP_ONESIGNAL_APP_ID
ENV REACT_APP_ONESIGNAL_SAFARI_WEB_ID=$REACT_APP_ONESIGNAL_SAFARI_WEB_ID
ENV REACT_APP_OIDC_CLIENT_ID=$REACT_APP_OIDC_CLIENT_ID
ENV REACT_APP_OIDC_REDIRECT_URI=$REACT_APP_OIDC_REDIRECT_URI

ENV NODE_ENV=production

COPY . .

RUN yarn install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
