apiVersion: v1
kind: Service
metadata:
  name: bestande-web
  namespace: bestande
spec:
  type: NodePort
  selector:
    app: bestande-web
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    nodePort: 30002
