export const UPDATE_MODULE_UZH = 'UPDATE_MODULE_UZH';
export const UPDATE_MODULE_ETH = 'UPDATE_MODULE_ETH';
export const UPDATE_TIMETABLE = 'UPDATE_TIMETABLE';
export const UPDATE_ROOM_UZH = 'UPDATE_ROOM_UZH';
export const UPDATE_ROOM_ETH = 'UPDATE_ROOM_ETH';
export const UPDATE_DEPARTMENTS_ETH = 'UPDATE_DEPARTMENTS_ETH';
export const COUNT_USERS = 'COUNT_USERS';

export const CREATE_USER_COUNT_TASK = 'CREATE_USER_COUNT_TASK';
export const CREATE_TIMETABLE_TASKS = 'CREATE_TIMETABLE_TASKS';
export const CREATE_UPDATE_UZH_TASKS = 'CREATE_UPDATE_UZH_TASKS';
export const CREATE_UPDATE_ETH_TASKS = 'CREATE_UPDATE_ETH_TASKS';

export const CREATE_UPDATE_ROOMS_TASK = 'CREATE_UPDATE_ROOMS_TASK';
export const COUNT_PROMOTION_IMPRESSION = 'COUNT_PROMOTION_IMPRESSION';

export const CREATE_UPDATE_PROMOTION_IMPRESSIONS_TASKS =
	'CREATE_UPDATE_PROMOTION_IMPRESSIONS_TASKS';

export const CREATE_UPDATE_DEPARTMENTS_ETH_TASKS =
	'CREATE_UPDATE_DEPARTMENTS_ETH_TASKS';
