export const minimumFields = {
	name: true,
	short_name: true,
	'semesters.period': true,
	'semesters.period_human': true,
	'semesters.description': true,
	'semesters.credits': true,
	uni_identifier: true,
	institution: true,
	university: true,
	faculty: true,
	departments: true,
	userCount: true,
	ratingSummary: true,
	gradeStatistics: true,
	courseCode: true,
	type: true,
	slug: true,
};
