fastlane_version "2.119.0"

platform :ios do 	
	
	lane :certificates do
		api_key = app_store_connect_api_key(
			key_id: "6CF28Z2CUR",
			issuer_id: "69a6de80-96d0-47e3-e053-5b8c7c11a4d1",
			key_filepath: "./fastlane/AuthKey_6CF28Z2CUR.p8",
			in_house: false
		)
		match(
			type: "appstore",
			readonly: true,
			api_key: api_key
		)
	end

	lane :ship do	
		api_key = app_store_connect_api_key(
			key_id: "6CF28Z2CUR",
			issuer_id: "69a6de80-96d0-47e3-e053-5b8c7c11a4d1",
			key_filepath: "./fastlane/AuthKey_6CF28Z2CUR.p8",
			in_house: false
		)	
		pilot(
			skip_waiting_for_build_processing: true,
			api_key: api_key
		)
		slack(
			message: "[Bestande] New Beta for iOS",
			channel: '#bestande-beta'
		)
	end

	lane :increment do
		increment_build_number({
			build_number: sh('curl -s https://increment.build/bestande-ios-68840f10'),
			xcodeproj: './ios/BestandeReact.xcodeproj'

		})
	end

	lane :build do		
		gym(
			scheme: 'BestandeReact',
			configuration: "Release",
			export_method: "app-store",
			workspace: './ios/BestandeReact.xcworkspace',
			suppress_xcode_output: true
		)
	end

	lane :ci do
		setup_circle_ci
		certificates
		increment
		build
		ship
	end	

	error do |lane, exception|
			slack(
				message: '[Bestnade]' +  exception.message,
				success: false,
				channel: '#bestande-beta'
			)
	end
end

platform :android do

	lane :upload do
		supply(
			track: "alpha",
			skip_upload_apk: true,
			skip_upload_metadata: true,
			skip_upload_images: true,
			skip_upload_screenshots: true,
			skip_upload_changelogs: true
		)
		slack(
			message: 'New Beta for Android uploaded to Play Store',
			channel: '#bestande-beta',
		)
	end

	lane :ci do
		sh "cd .. && rm -rf build"
    gradle(
			task: "clean",
			project_dir: 'android/'
		)
    gradle(
			task: "bundle",
			project_dir: 'android/',
			properties: {
				'versionCode': sh('curl -s https://increment.build/bestande-android-68840f10')
			},
			flavor: "production",
			build_type: "Release"
		)
		upload
	end

  error do |lane, exception|
    slack(
      message: exception.message,
			success: false,
			channel: '#bestande-beta'
    )
  end
end
