name: Docker Build

on:
    push:
        branches:
            - main
            - production
    pull_request:
        branches:
            - main
            - production

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image
              run: |
                  docker build -t dummy:latest .

    check:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Check if Docker build passed
              run: echo "Docker build passed"
